feat: add validation for openwebui-ollama use case in the testing scr… (#542)

diff --git a/.github/workflows/use-cases.yml b/.github/workflows/use-cases.yml
--- a/.github/workflows/use-cases.yml
+++ b/.github/workflows/use-cases.yml
@@ -146,3 +146,56 @@ jobs:
           path: |
             validation_report.csv
             validation_run.log
+
+  validate-openwebui-ollama:
+    runs-on: [self-hosted, case-cse, arlh]
+    needs: precheck
+    if: needs.precheck.outputs.should_run == 'true'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run validation
+        env:
+          no_proxy: localhost, 127.0.0.1
+        run: |
+          cd ${{ github.workspace }}
+          echo "Running validation for openwebui-ollama..."
+          if [[ -f validation_report.csv ]]; then
+            rm validation_report.csv
+          fi
+          if [[ -f validation_run.log ]]; then
+            rm validation_run.log
+          fi
+          docker system prune -af
+          .github/tests/validate-use-cases.sh -u openwebui-ollama 2>&1 | tee validation_run.log
+          if [ $? -ne 0 ]; then
+            echo "Validation for openwebui-ollama failed."
+            exit 1
+          fi
+
+      - name: Validate report
+        run: |
+          echo "Validating use cases report..."
+          cd ${{ github.workspace }}
+          if [ ! -f validation_report.csv ]; then
+            echo "Validation report not found."
+            exit 1
+          fi
+
+          # Check if the report contains FAIL
+          if grep -q "FAIL" validation_report.csv; then
+            echo "Validation report contains FAIL."
+            exit 1
+          fi
+
+          echo "All validation for use cases pass."
+
+      - name: Upload report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: OpenWebUI Ollama Validation Report
+          path: |
+            validation_report.csv
+            validation_run.log
