534 user story create validation script for ai video analytics use case (#539)
* feat: add validation for ai-video-analytics use case in CI workflow

* feat: streamline validation process by removing unnecessary build steps and adding docker cleanup

diff --git a/.github/workflows/use-cases.yml b/.github/workflows/use-cases.yml
--- a/.github/workflows/use-cases.yml
+++ b/.github/workflows/use-cases.yml
@@ -42,7 +42,7 @@ jobs:
           echo "should_run=$should_run" >> $GITHUB_OUTPUT
 
   validate-rag-toolkit:
-    runs-on: [self-hosted, case-cse, arls-a770]
+    runs-on: [self-hosted, case-cse, arlh]
     needs: precheck
     if: needs.precheck.outputs.should_run == 'true'
     steps:
@@ -61,6 +61,7 @@ jobs:
           if [[ -f validation_run.log ]]; then
             rm validation_run.log
           fi
+          docker system prune -af
           .github/tests/validate-use-cases.sh -u rag-toolkit 2>&1 | tee validation_run.log
           if [ $? -ne 0 ]; then
             echo "Validation for rag toolkit failed."
@@ -92,4 +93,56 @@ jobs:
           path: |
             validation_report.csv
             validation_run.log
-            
+
+  validate-ai-video-analytics:
+    runs-on: [self-hosted, case-cse, arlh]
+    needs: precheck
+    if: needs.precheck.outputs.should_run == 'true'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run validation
+        env:
+          no_proxy: localhost, 127.0.0.1
+        run: |
+          cd ${{ github.workspace }}
+          echo "Running validation for ai video analytics..."
+          if [[ -f validation_report.csv ]]; then
+            rm validation_report.csv
+          fi
+          if [[ -f validation_run.log ]]; then
+            rm validation_run.log
+          fi
+          docker system prune -af
+          .github/tests/validate-use-cases.sh -u ai-video-analytics 2>&1 | tee validation_run.log
+          if [ $? -ne 0 ]; then
+            echo "Validation for ai video analytics failed."
+            exit 1
+          fi
+
+      - name: Validate report
+        run: |
+          echo "Validating use cases report..."
+          cd ${{ github.workspace }}
+          if [ ! -f validation_report.csv ]; then
+            echo "Validation report not found."
+            exit 1
+          fi
+
+          # Check if the report contains FAIL
+          if grep -q "FAIL" validation_report.csv; then
+            echo "Validation report contains FAIL."
+            exit 1
+          fi
+
+          echo "All validation for use cases pass."
+
+      - name: Upload report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: AI Video Analytics Validation Report
+          path: |
+            validation_report.csv
+            validation_run.log
